---
title: "Tipos de filme de FULANO(A)"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(cluster)
library(plotly)
library(ggdendro)

source(here::here("code/lib.R"))
theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = TRUE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r}
## ANTES DE USAR
# Para criar data/movies.csv
import_data("natalie_portman") # ou com o ator/atriz que você escolher
```


```{r read}
filmes = read_imported_data()
```

## Descrição

```{r}



p <- plot_ly(filmes, x = filmes$bilheteria , y = filmes$ano, text = filmes$filme, type = 'scatter', mode = 'markers', color = filmes$avaliacao, colors = 'Reds',
        marker = list(size = 20, opacity = 0.5)) %>%
  layout(title = 'Gender Gap in Earnings per University',
         xaxis = list(showgrid = FALSE),
         yaxis = list(showgrid = FALSE))




ggplotly(p)



```


## Usar barras pra comparar por ano
 

```{r}

p <- plot_ly(filmes, x = filmes$filme, y = filmes$avaliacao, type = 'bar', name = 'SF Zoo') %>%
  add_trace(y = filmes$ano, name = 'LA Zoo') %>%
  layout(yaxis = list(title = 'Count'), barmode = 'group')

ggplotly(p)
```
```{r}
p <- plot_ly(filmes, x = filmes$ano, y = filmes$avaliacao, type = 'scatter', mode = 'lines')
ggplotly(p)
```


## Estrutura de grupos?

```{r}
p = filmes %>% 
    ggplot(aes(x = "", y = bilheteria, label = filme)) + 
    geom_jitter(width = .05, alpha = .3, size = 3) + 
    labs(x = "")

ggplotly(p)
```


```{r}
get_grupos <- function(agrupamento, num_grupos){
    agrupamento %>% 
        cutree(num_grupos) %>% 
        as.data.frame() %>% 
        mutate(label = rownames(.)) %>% 
        gather(key =  "k", value = "grupo", -label) %>% 
        mutate(grupo = as.character(grupo))
}

atribuicoes = get_grupos(agrupamento_h, num_grupos = 1:6)

atribuicoes = atribuicoes %>% 
    left_join(filmes, by = c("label" = "filme"))

atribuicoes %>% 
    ggplot(aes(x = "Filmes", y = avaliacao, colour = grupo)) + 
    geom_jitter(width = .02, height = 0, size = 1.6, alpha = .6) + 
    facet_wrap(~ paste(k, " grupos")) + 
    scale_color_brewer(palette = "Dark2")

```



